- hosts: Log
  tasks:
    - name: Create The app directory for docker compose
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Copy required files for monitoring
      ansible.builtin.copy:
        src: "logging/{{ item }}"
        dest: /app
      loop:
        - docker-compose.yaml
