---
- hosts: para
  roles:
    - role: patrickjahns.promtail
      vars:
        promtail_config_clients:
          - url: "174.138.49.236"
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*log

 
 