route:

  group_by: ['...']

  group_wait: 1s

  group_interval: 5m

  repeat_interval: 1m

  receiver: discord

  routes:
  - receiver: discord
    continue: true  

receivers:
  - name: 'discord'
    webhook_configs:
      - url: http://app:5000/
        http_config: {}
