- hosts: testdrops
  roles:
    - role: do1jlr.restic
      vars:
        restic_create_schedule: true
        restic_create_cron: true
        restic_schedule_type: cronjob
        restic_repos:
          remote:
            location: "{{ lookup('env', 'LOCATION') }}"
            password: "{{ lookup('env', 'RESTIC_PASSWORD') }}"
            aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
            aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
            aws_default_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
            init: true
        restic_backups:
          etc:
            name: etc
            repo: remote
            src: /etc/
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
          var:
            name: var
            repo: remote
            src: /var/
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
            
          root:
            name: root
            repo: remote
            src: /root
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
            
          services:
            name: services
            repo: remote
            src: /services
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
            
          usr_local_bin:
            name: usr_local_bin
            repo: remote
            src: /usr/local/bin/
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
            
          srv:
            name: srv
            repo: remote
            src: /srv
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
            
          opt:
            name: opt
            repo: remote
            src: /srv
            scheduled: true
            schedule_minute: 0
            schedule_hour: 9
            schedule_weekday: 1
            schedule_month: '*'
        restic_no_log: false
